In [2]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [3]:
reshaped = arr.reshape(3,4)
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
flattened = reshaped.flatten()
flattened 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
revel =reshaped.ravel()
revel[1]=20
revel

array([ 1, 20,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
reshaped

array([[ 1, 20,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
arr1=np.array([1,2,3])
print(arr1)
arr2=np.array([1,2,3])
print(arr2)

[1 2 3]
[1 2 3]


In [8]:
arr1+arr2

array([2, 4, 6])

In [9]:
arr1+4

array([5, 6, 7])

In [10]:
arr1=np.array([1,2,3])
print(arr1)
arr2=np.array([[1],[2],[3]])
print(arr2)

[1 2 3]
[[1]
 [2]
 [3]]
