In [96]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [97]:
reshaped = arr.reshape(3,4)
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [98]:
flattened = reshaped.flatten()
flattened 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [99]:
revel =reshaped.ravel()
revel[1]=20
revel

array([ 1, 20,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [100]:
reshaped

array([[ 1, 20,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [101]:
arr1=np.array([1,2,3])
print(arr1)
arr2=np.array([1,2,3])
print(arr2)

[1 2 3]
[1 2 3]


In [102]:
arr1+arr2

array([2, 4, 6])

In [103]:
arr1+4

array([5, 6, 7])

In [104]:
arr1=np.array([1,2,3])
print(arr1)
arr2=np.array([[1],[2],[3]])
print(arr2)

[1 2 3]
[[1]
 [2]
 [3]]


In [105]:
import numpy as np
import pandas as pd

In [106]:
np.random.seed(42)
apartments=[f"Apt_{i})" for i in range (1,21)]
apartments

['Apt_1)',
 'Apt_2)',
 'Apt_3)',
 'Apt_4)',
 'Apt_5)',
 'Apt_6)',
 'Apt_7)',
 'Apt_8)',
 'Apt_9)',
 'Apt_10)',
 'Apt_11)',
 'Apt_12)',
 'Apt_13)',
 'Apt_14)',
 'Apt_15)',
 'Apt_16)',
 'Apt_17)',
 'Apt_18)',
 'Apt_19)',
 'Apt_20)']

In [107]:
datas=pd.date_range(start="2021-07-01",periods=10,freq="D")

In [108]:
datas

DatetimeIndex(['2021-07-01', '2021-07-02', '2021-07-03', '2021-07-04',
               '2021-07-05', '2021-07-06', '2021-07-07', '2021-07-08',
               '2021-07-09', '2021-07-10'],
              dtype='datetime64[ns]', freq='D')

In [109]:
data={
    "date":np.tile(datas,len(apartments)),
    "apartments":np.repeat(apartments,len(datas)),
    "Electricity_usage":np.random.normal(loc=20,scale=5,size=len(datas)*len(apartments))
}
data

{'date': array(['2021-07-01T00:00:00.000000000', '2021-07-02T00:00:00.000000000',
        '2021-07-03T00:00:00.000000000', '2021-07-04T00:00:00.000000000',
        '2021-07-05T00:00:00.000000000', '2021-07-06T00:00:00.000000000',
        '2021-07-07T00:00:00.000000000', '2021-07-08T00:00:00.000000000',
        '2021-07-09T00:00:00.000000000', '2021-07-10T00:00:00.000000000',
        '2021-07-01T00:00:00.000000000', '2021-07-02T00:00:00.000000000',
        '2021-07-03T00:00:00.000000000', '2021-07-04T00:00:00.000000000',
        '2021-07-05T00:00:00.000000000', '2021-07-06T00:00:00.000000000',
        '2021-07-07T00:00:00.000000000', '2021-07-08T00:00:00.000000000',
        '2021-07-09T00:00:00.000000000', '2021-07-10T00:00:00.000000000',
        '2021-07-01T00:00:00.000000000', '2021-07-02T00:00:00.000000000',
        '2021-07-03T00:00:00.000000000', '2021-07-04T00:00:00.000000000',
        '2021-07-05T00:00:00.000000000', '2021-07-06T00:00:00.000000000',
        '2021-07-07T00:00:00.0

In [110]:
df=pd.DataFrame(data)
df

date apartments  Electricity_usage
0   2021-07-01     Apt_1)          22.483571
1   2021-07-02     Apt_1)          19.308678
2   2021-07-03     Apt_1)          23.238443
3   2021-07-04     Apt_1)          27.615149
4   2021-07-05     Apt_1)          18.829233
..         ...        ...                ...
195 2021-07-06    Apt_20)          21.926587
196 2021-07-07    Apt_20)          15.580713
197 2021-07-08    Apt_20)          20.768626
198 2021-07-09    Apt_20)          20.291044
199 2021-07-10    Apt_20)          14.285149

[200 rows x 3 columns]

In [111]:
print(df.describe)

<bound method NDFrame.describe of           date apartments  Electricity_usage
0   2021-07-01     Apt_1)          22.483571
1   2021-07-02     Apt_1)          19.308678
2   2021-07-03     Apt_1)          23.238443
3   2021-07-04     Apt_1)          27.615149
4   2021-07-05     Apt_1)          18.829233
..         ...        ...                ...
195 2021-07-06    Apt_20)          21.926587
196 2021-07-07    Apt_20)          15.580713
197 2021-07-08    Apt_20)          20.768626
198 2021-07-09    Apt_20)          20.291044
199 2021-07-10    Apt_20)          14.285149

[200 rows x 3 columns]>


In [112]:
print(df.dtypes)

date                 datetime64[ns]
apartments                   object
Electricity_usage           float64
dtype: object


In [114]:
usage_per_apartments = df.groupby("apartments")["Electricity_usage"].sum().sort_values(ascending=False)
print(usage_per_apartments)

apartments
Apt_1)     222.403056
Apt_18)    217.923240
Apt_17)    216.231011
Apt_6)     209.972071
Apt_16)    207.663743
Apt_12)    206.893698
Apt_9)     205.072372
Apt_13)    203.496211
Apt_7)     199.247150
Apt_8)     197.613194
Apt_11)    197.528127
Apt_15)    197.074889
Apt_10)    192.540430
Apt_20)    190.609216
Apt_3)     188.907822
Apt_19)    188.546976
Apt_5)     187.358891
Apt_14)    185.185183
Apt_4)     184.494667
Apt_2)     160.467088
Name: Electricity_usage, dtype: float64


In [118]:
print(df.columns)

Index(['date', 'apartments', 'Electricity_usage'], dtype='object')


In [119]:
daily_avg = df.groupby("date")["Electricity_usage"].mean()
print(daily_avg.head())

date
2021-07-01    19.104638
2021-07-02    20.955763
2021-07-03    19.444996
2021-07-04    19.216791
2021-07-05    18.980068
Name: Electricity_usage, dtype: float64


In [125]:
import matplotlib.pyplot as plt 
import seaborn as sns

In [ ]:
plt.figure()

NameError: name 'figures' is not defined