In [50]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [51]:
reshaped = arr.reshape(3,4)
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
flattened = reshaped.flatten()
flattened 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [53]:
revel =reshaped.ravel()
revel[1]=20
revel

array([ 1, 20,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
reshaped

array([[ 1, 20,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
arr1=np.array([1,2,3])
print(arr1)
arr2=np.array([1,2,3])
print(arr2)

[1 2 3]
[1 2 3]


In [56]:
arr1+arr2

array([2, 4, 6])

In [57]:
arr1+4

array([5, 6, 7])

In [58]:
arr1=np.array([1,2,3])
print(arr1)
arr2=np.array([[1],[2],[3]])
print(arr2)

[1 2 3]
[[1]
 [2]
 [3]]


In [65]:
import numpy as np
import pandas as pd

In [60]:
np.random.seed(42)
apartments=[f"Apt_(i)"for i in range (1,21)]

In [81]:
datas=pd.date_range(start="2021-07-01",periods=10,freq="D")

In [62]:
datas

DatetimeIndex(['2021-07-01', '2021-07-02', '2021-07-03', '2021-07-04',
               '2021-07-05', '2021-07-06', '2021-07-07', '2021-07-08',
               '2021-07-09', '2021-07-10', '2021-07-11', '2021-07-12',
               '2021-07-13', '2021-07-14', '2021-07-15', '2021-07-16',
               '2021-07-17', '2021-07-18', '2021-07-19', '2021-07-20',
               '2021-07-21', '2021-07-22', '2021-07-23', '2021-07-24',
               '2021-07-25', '2021-07-26', '2021-07-27', '2021-07-28',
               '2021-07-29', '2021-07-30'],
              dtype='datetime64[ns]', freq='D')

In [83]:
data={
    "date":np.tile(datas,len(apartments)),
    "apartments":np.repeat(apartments,len(datas)),
    "Electricity_usage":np.random.normal(loc=20,scale=5,size=len(datas)*len(apartments))
}
data

{'date': array(['2021-07-01T00:00:00.000000000', '2021-07-02T00:00:00.000000000',
        '2021-07-03T00:00:00.000000000', '2021-07-04T00:00:00.000000000',
        '2021-07-05T00:00:00.000000000', '2021-07-06T00:00:00.000000000',
        '2021-07-07T00:00:00.000000000', '2021-07-08T00:00:00.000000000',
        '2021-07-09T00:00:00.000000000', '2021-07-10T00:00:00.000000000',
        '2021-07-01T00:00:00.000000000', '2021-07-02T00:00:00.000000000',
        '2021-07-03T00:00:00.000000000', '2021-07-04T00:00:00.000000000',
        '2021-07-05T00:00:00.000000000', '2021-07-06T00:00:00.000000000',
        '2021-07-07T00:00:00.000000000', '2021-07-08T00:00:00.000000000',
        '2021-07-09T00:00:00.000000000', '2021-07-10T00:00:00.000000000',
        '2021-07-01T00:00:00.000000000', '2021-07-02T00:00:00.000000000',
        '2021-07-03T00:00:00.000000000', '2021-07-04T00:00:00.000000000',
        '2021-07-05T00:00:00.000000000', '2021-07-06T00:00:00.000000000',
        '2021-07-07T00:00:00.0

In [84]:
df=pd.DataFrame(data)
df

date apartments  Electricity_usage
0   2021-07-01    Apt_(i)          21.252464
1   2021-07-02    Apt_(i)          21.732241
2   2021-07-03    Apt_(i)          16.599876
3   2021-07-04    Apt_(i)          21.161268
4   2021-07-05    Apt_(i)          21.465362
..         ...        ...                ...
195 2021-07-06    Apt_(i)          21.160250
196 2021-07-07    Apt_(i)          12.759578
197 2021-07-08    Apt_(i)          12.962681
198 2021-07-09    Apt_(i)          16.407779
199 2021-07-10    Apt_(i)          18.932764

[200 rows x 3 columns]